### ISSUE TITLE
Licence unspecified ?

### ISSUE THREAD

**Issue by rzr** [BootCampOSV/bcosv#6]
Please select a libre licence  before merging contributions

As I said at CampOsv it would makes sense to chose one already validated by other community : 

https://wiki.debian.org/DFSGLicenses

https://spdx.org/licenses/

**Comment by buguen** [comment]
Yes  I know, I am concerned about that point. 
I suggest a MIT license. 
Is It fine for everyone ? 
I do not exactly which owners to precise, For now I have specified BootCampOSV.

**Comment by rzr** [comment]
I am not yet a contributor of project yet but that's a good suggestion , So contact each commiters, add the file here and ask current pull request to rebase on it.

If some content want be in other licence please mention it explicitly , other licence should be compatibles together (see my upper links).

**Comment by rzr** [comment]
https://github.com/BootCampOSV/bcosv/blob/master/License
